# fly.toml app configuration file generated for visitantesonoro on 2023-09-28T00:19:37-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "visitantesonoro"
primary_region = "bog"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
